# Generated by Django 4.2.4 on 2023-08-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeightDepthRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('depth', models.FloatField()),
            ],
            options={
                'unique_together': {('weight', 'depth')},
            },
        ),
    ]
